nuevoo commit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,6 +12,12 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
       
+    - name: Install Docker Compose
+      run: |
+        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+        sudo chmod +x /usr/local/bin/docker-compose
+        docker-compose --version
+        
     - name: Sign in to Docker Hub
       uses: docker/login-action@v2
       with:
@@ -24,12 +30,16 @@ jobs:
         
         for service in "${services[@]}"
         do
-          if [ -d "$service" ]; then
-            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
-            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
+          if git diff --quiet HEAD^ HEAD -- $service/; then
+            echo "No changes detected in $service, skipping build and push."
           else
-            echo "Could not find directory for service $service"
-            exit 1
+            if [ -d "$service" ]; then
+              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
+              docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
+            else
+              echo "Could not find directory for service $service"
+              exit 1
+            fi
           fi
         done
 
@@ -42,6 +52,7 @@ jobs:
     - name: Execute Docker Compose
       run: |
         docker-compose -f ./docker/docker-compose.yml up -d
+
   deploy-encrypt-information:
     runs-on: ubuntu-latest
     needs: build-and-push
@@ -53,8 +64,8 @@ jobs:
     - name: Deploy to Azure Web App 1
       uses: azure/webapps-deploy@v2
       with:
-        app-name: 'encryptinformation'
+        app-name: 'encrypt-information'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_1 }}
         images: '${{ secrets.DOCKERHUB_USERNAME }}/encrypt-information:latest'
 
- 
+        
